/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.CategoriaController;
import br.ulbra.model.Categoria;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeferson Leon
 */
public class FrmCategoria extends javax.swing.JDialog {

    /**
     * Creates new form Categoria
     */
    public FrmCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        CategoriaController categoriaController = new CategoriaController();
        List<Categoria> listaCategoria = new ArrayList();
        listaCategoria = categoriaController.getTodosCategoriaController();
        this.popularTabelaCategoria(listaCategoria);
    }

    private void popularTabelaCategoria(List<Categoria> pListaDeCategoria) {
        DefaultTableModel modelo = new DefaultTableModel();
        this.JtableCategoria.setModel(modelo);
        modelo.addColumn("Código");
        modelo.addColumn("Descrição");
        for (Categoria categoria : pListaDeCategoria) {
            modelo.addRow(
                    new Object[]{
                        categoria.getId_categoria(),
                        categoria.getDescricao()
                    }
            );
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableCategoria = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        txtCod.setEditable(false);

        jLabel2.setText("Descrição");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        JtableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(JtableCategoria);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btEditar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btEditar))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        CategoriaController filmeController = new CategoriaController();

        Categoria categoria = this.getDadosInterface();

        int idCategoriaSalvo = filmeController.salvarCategoriaController(categoria);

        if (idCategoriaSalvo > 0) {
            this.resetForm();
            List<Categoria> listaDeCategoria = filmeController.getTodosCategoriaController();

            this.popularTabelaCategoria(listaDeCategoria);

            JOptionPane.showMessageDialog(this, "Categoria salvo com sucesso!");
        } else {
            //erro ao salvar o filme
            JOptionPane.showMessageDialog(this, "Erro ao salvar Categoria");
        }

      
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void resetForm() {
        this.txtCod.setText(null);
        this.txtDescricao.setText(null);

    }
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         DefaultTableModel modeloTabelaCategoria = (DefaultTableModel) this.JtableCategoria.getModel();

        int linha = this.JtableCategoria.getSelectedRow();
        /* JOptionPane.showMessageDialog(null, linha);*/
       int idCategoria = Integer.parseInt(String.valueOf(modeloTabelaCategoria.getValueAt(linha, 0)));

        CategoriaController categoriaController = new CategoriaController();

        Categoria categoria = new Categoria();
        categoria.setId_categoria(idCategoria);

        boolean resultado = categoriaController.deleteCategoriaController(categoria);
        ;
        if (resultado == true) {
            modeloTabelaCategoria.removeRow(linha);

            JOptionPane.showMessageDialog(this, "Categoria Excluida com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir categoria");
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        Categoria categoria = new Categoria();
        CategoriaController categoriaController = new CategoriaController();
        DefaultTableModel modeloTabelaCategoria = (DefaultTableModel) this.JtableCategoria.getModel();
        int linha = this.JtableCategoria.getSelectedRow();
        categoria.setId_categoria(Integer.parseInt(String.valueOf(modeloTabelaCategoria.getValueAt(linha, 0))));
        categoria.setDescricao(String.valueOf(modeloTabelaCategoria.getValueAt(linha, 1)));

        this.setDadosInterface(categoria);


    }//GEN-LAST:event_btEditarActionPerformed

    private void setDadosInterface(Categoria categoria) {
        this.txtCod.setText(String.valueOf(categoria.getId_categoria()));
        this.txtDescricao.setText(categoria.getDescricao());
    }

    private Categoria getDadosInterface() {
      Categoria categoria = new Categoria();

        categoria.setId_categoria(0);
        if (this.txtCod.getText() != null) {
            if (!this.txtCod.getText().isEmpty()) {
                categoria.setId_categoria(Integer.parseInt(this.txtCod.getText()));
            }
        }

        categoria.setDescricao(this.txtDescricao.getText());
        

        return categoria;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCategoria dialog = new FrmCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableCategoria;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
